# Generated by Django 4.2.7 on 2025-11-10 21:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("routes", "0001_initial"),
        ("vehicles", "0002_vehicle_current_driver"),
        ("collection_points", "0003_collectionpointphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(max_length=200, verbose_name="Nome do Motorista"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Data Agendada")),
                ("scheduled_time", models.TimeField(verbose_name="Horário Agendado")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Início"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Término"
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Peso Total Coletado (kg)",
                    ),
                ),
                (
                    "distance_traveled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Distância Percorrida (km)",
                    ),
                ),
                (
                    "fuel_consumed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Combustível Consumido (L)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="routes.route",
                        verbose_name="Rota",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="vehicles.vehicle",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coleta",
                "verbose_name_plural": "Coletas",
                "db_table": "collections",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collected",
                    models.BooleanField(default=False, verbose_name="Coletado"),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Coletado em"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Peso Coletado (kg)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="collections.collection",
                        verbose_name="Coleta",
                    ),
                ),
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="collection_points.collectionpoint",
                        verbose_name="Ponto de Coleta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Coleta",
                "verbose_name_plural": "Itens de Coleta",
                "db_table": "collection_items",
                "ordering": ["order", "id"],
            },
        ),
    ]
