# Generated by Django 4.2.7 on 2025-11-10 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="collection",
            table="route_collections",
        ),
        migrations.AlterModelTable(
            name="collectionitem",
            table="route_collection_items",
        ),
    ]
