# Generated by Django 4.2.7 on 2025-11-10 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0004_alter_driver_address_alter_driver_birth_date_and_more"),
        ("collections", "0002_alter_collection_table_alter_collectionitem_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="actual_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário Real de Término"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="actual_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário Real de Início"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collections",
                to="vehicles.driver",
                verbose_name="Motorista",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="waste_collected_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Volume Coletado (m³)",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="waste_collected_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Peso Coletado Informado (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="driver_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome do Motorista (legado)"
            ),
        ),
    ]
