# Generated by Django 4.2.7 on 2025-10-06 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
