# Generated by Django 4.2.7 on 2025-10-05 19:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome da Rota")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diária"),
                            ("weekly", "Semanal"),
                            ("biweekly", "Quinzenal"),
                            ("monthly", "Mensal"),
                        ],
                        max_length=20,
                        verbose_name="Frequência",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativa"),
                            ("inactive", "Inativa"),
                            ("maintenance", "Em Manutenção"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        srid=4326, verbose_name="Geometria da Rota"
                    ),
                ),
                (
                    "estimated_duration",
                    models.DurationField(verbose_name="Duração Estimada"),
                ),
                (
                    "estimated_distance",
                    models.FloatField(verbose_name="Distância Estimada (km)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rota",
                "verbose_name_plural": "Rotas",
                "db_table": "routes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RouteOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optimized_geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        srid=4326, verbose_name="Geometria Otimizada"
                    ),
                ),
                (
                    "original_distance",
                    models.FloatField(verbose_name="Distância Original (km)"),
                ),
                (
                    "optimized_distance",
                    models.FloatField(verbose_name="Distância Otimizada (km)"),
                ),
                (
                    "distance_saved",
                    models.FloatField(verbose_name="Distância Economizada (km)"),
                ),
                (
                    "original_duration",
                    models.DurationField(verbose_name="Duração Original"),
                ),
                (
                    "optimized_duration",
                    models.DurationField(verbose_name="Duração Otimizada"),
                ),
                (
                    "algorithm_used",
                    models.CharField(max_length=50, verbose_name="Algoritmo Utilizado"),
                ),
                ("optimization_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_applied",
                    models.BooleanField(default=False, verbose_name="Aplicada"),
                ),
                (
                    "applied_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aplicação"
                    ),
                ),
                (
                    "original_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimizations",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otimização de Rota",
                "verbose_name_plural": "Otimizações de Rotas",
                "db_table": "route_optimizations",
                "ordering": ["-optimization_date"],
            },
        ),
        migrations.CreateModel(
            name="RouteExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Data Agendada")),
                ("scheduled_time", models.TimeField(verbose_name="Horário Agendado")),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Início Real"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim Real"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "actual_distance",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distância Real (km)"
                    ),
                ),
                (
                    "fuel_consumed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Combustível Consumido (L)"
                    ),
                ),
                (
                    "waste_collected",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Resíduos Coletados (kg)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driven_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="routes.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_executions",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execução de Rota",
                "verbose_name_plural": "Execuções de Rotas",
                "db_table": "route_executions",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="RouteSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Dia da Semana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Horário de Início")),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Manhã"),
                            ("afternoon", "Tarde"),
                            ("night", "Noite"),
                        ],
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento de Rota",
                "verbose_name_plural": "Agendamentos de Rotas",
                "db_table": "route_schedules",
                "unique_together": {("route", "day_of_week", "start_time")},
            },
        ),
    ]
