# Generated by Django 4.2.7 on 2025-10-05 19:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("routes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("container", "Contêiner"),
                            ("bin", "Lixeira"),
                            ("dumpster", "Caçamba"),
                            ("residential", "Residencial"),
                            ("commercial", "Comercial"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Localização"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Endereço")),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "capacity_volume",
                    models.FloatField(verbose_name="Capacidade de Volume (m³)"),
                ),
                (
                    "capacity_weight",
                    models.FloatField(verbose_name="Capacidade de Peso (kg)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("maintenance", "Em Manutenção"),
                            ("full", "Cheio"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_fill_level",
                    models.FloatField(
                        default=0, verbose_name="Nível de Preenchimento (%)"
                    ),
                ),
                (
                    "collection_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diária"),
                            ("weekly", "Semanal"),
                            ("biweekly", "Quinzenal"),
                            ("monthly", "Mensal"),
                        ],
                        max_length=20,
                        verbose_name="Frequência de Coleta",
                    ),
                ),
                (
                    "last_collection",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Coleta"
                    ),
                ),
                (
                    "next_collection",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Próxima Coleta"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto de Coleta",
                "verbose_name_plural": "Pontos de Coleta",
                "db_table": "collection_points",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WasteType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "color",
                    models.CharField(
                        help_text="Ex: #FF0000", max_length=7, verbose_name="Cor (hex)"
                    ),
                ),
                (
                    "is_recyclable",
                    models.BooleanField(default=False, verbose_name="Reciclável"),
                ),
                (
                    "is_hazardous",
                    models.BooleanField(default=False, verbose_name="Perigoso"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Resíduo",
                "verbose_name_plural": "Tipos de Resíduos",
                "db_table": "waste_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CollectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection_date",
                    models.DateTimeField(verbose_name="Data/Hora da Coleta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collected", "Coletado"),
                            ("partially_collected", "Parcialmente Coletado"),
                            ("not_collected", "Não Coletado"),
                            ("inaccessible", "Inacessível"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "weight_collected",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso Coletado (kg)"
                    ),
                ),
                (
                    "volume_collected",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Volume Coletado (m³)"
                    ),
                ),
                (
                    "fill_level_before",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nível Antes (%)"
                    ),
                ),
                (
                    "fill_level_after",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nível Depois (%)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="collection_photos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "collection_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Localização da Coleta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="collection_points.collectionpoint",
                    ),
                ),
                (
                    "route_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="routes.routeexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Coleta",
                "verbose_name_plural": "Registros de Coletas",
                "db_table": "collection_records",
                "ordering": ["-collection_date"],
            },
        ),
        migrations.CreateModel(
            name="CollectionPointWasteType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Tipo Principal"),
                ),
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_types",
                        to="collection_points.collectionpoint",
                    ),
                ),
                (
                    "waste_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_points",
                        to="collection_points.wastetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Resíduo do Ponto",
                "verbose_name_plural": "Tipos de Resíduos dos Pontos",
                "db_table": "collection_point_waste_types",
                "unique_together": {("collection_point", "waste_type")},
            },
        ),
        migrations.CreateModel(
            name="CollectionPointRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_order",
                    models.IntegerField(verbose_name="Ordem na Sequência"),
                ),
                (
                    "estimated_collection_time",
                    models.DurationField(verbose_name="Tempo Estimado de Coleta"),
                ),
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="collection_points.collectionpoint",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_points",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto na Rota",
                "verbose_name_plural": "Pontos nas Rotas",
                "db_table": "collection_point_routes",
                "ordering": ["route", "sequence_order"],
                "unique_together": {("collection_point", "route")},
            },
        ),
    ]
