# Generated by Django 4.2.7 on 2025-11-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
        ("collection_points", "0003_collectionpointphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionrecord",
            name="route_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="routes.routeexecution",
            ),
        ),
    ]
