# Generated by Django 4.2.7 on 2025-11-12 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection_points", "0002_remove_fill_level"),
        ("collection_points", "0004_alter_collectionrecord_route_execution"),
    ]

    operations = []
