# Generated by Django 4.2.7 on 2025-10-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                ("model", models.CharField(max_length=50, verbose_name="Modelo")),
                ("brand", models.CharField(max_length=50, verbose_name="Marca")),
                ("year", models.IntegerField(verbose_name="Ano")),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("truck", "Caminhão"),
                            ("compactor", "Compactador"),
                            ("pickup", "Caminhonete"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "capacity_weight",
                    models.FloatField(verbose_name="Capacidade de Peso (kg)"),
                ),
                (
                    "capacity_volume",
                    models.FloatField(verbose_name="Capacidade de Volume (m³)"),
                ),
                (
                    "fuel_capacity",
                    models.FloatField(verbose_name="Capacidade do Tanque (L)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("maintenance", "Em Manutenção"),
                            ("inactive", "Inativo"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Manutenção"
                    ),
                ),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima Manutenção"
                    ),
                ),
                (
                    "purchase_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor de Compra",
                    ),
                ),
                (
                    "current_odometer",
                    models.FloatField(default=0, verbose_name="Odômetro Atual (km)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "db_table": "vehicles",
                "ordering": ["license_plate"],
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventiva"),
                            ("corrective", "Corretiva"),
                            ("emergency", "Emergencial"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Custo"
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Data Agendada")),
                (
                    "actual_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Realizada"
                    ),
                ),
                (
                    "odometer_reading",
                    models.FloatField(verbose_name="Leitura do Odômetro"),
                ),
                (
                    "technician",
                    models.CharField(max_length=100, verbose_name="Técnico"),
                ),
                (
                    "workshop",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Oficina"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Concluída"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção de Veículo",
                "verbose_name_plural": "Manutenções de Veículos",
                "db_table": "vehicle_maintenances",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleGPSTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                (
                    "speed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Velocidade (km/h)"
                    ),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Direção (graus)"
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Altitude (m)"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_tracks",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rastreamento GPS",
                "verbose_name_plural": "Rastreamentos GPS",
                "db_table": "vehicle_gps_tracks",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-timestamp"],
                        name="vehicle_gps_vehicle_94c84a_idx",
                    )
                ],
            },
        ),
    ]
