# Generated by Django 4.2.7 on 2025-11-10 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_vehicle_current_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato: 000.000.000-00",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("birth_date", models.DateField(verbose_name="Data de Nascimento")),
                (
                    "license_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número da CNH"
                    ),
                ),
                (
                    "license_category",
                    models.CharField(
                        choices=[
                            ("B", "Categoria B"),
                            ("C", "Categoria C"),
                            ("D", "Categoria D"),
                            ("E", "Categoria E"),
                        ],
                        max_length=2,
                        verbose_name="Categoria da CNH",
                    ),
                ),
                (
                    "license_expiration",
                    models.DateField(verbose_name="Validade da CNH"),
                ),
                ("hire_date", models.DateField(verbose_name="Data de Contratação")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("on_leave", "Afastado"),
                            ("inactive", "Inativo"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Endereço")),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                ("zip_code", models.CharField(max_length=9, verbose_name="CEP")),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Motorista",
                "verbose_name_plural": "Motoristas",
                "db_table": "drivers",
                "ordering": ["name"],
            },
        ),
    ]
