# Generated by Django 4.2.7 on 2025-11-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0003_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="zip_code",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
    ]
