# Generated by Django 4.2.7 on 2025-11-11 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0004_alter_driver_address_alter_driver_birth_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VehicleGPSTracker",
        ),
    ]
