# Generated by Django 4.2.7 on 2025-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0005_delete_vehiclegpstracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="capacity_volume",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Capacidade de Volume (m³)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="capacity_weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Capacidade de Peso (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_capacity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Capacidade do Tanque (L)"
            ),
        ),
    ]
